### ISSUE TITLE
Bad units in site file generation

### ISSUE THREAD

**Issue by deekaey** [cwerner/ldndctools#50]
- check depth attribute: should be in mm
- check corg and norg: should not be given as percentage but scale between 0-1 (1 would be 100%)
- define at least 4 strata even if they have identical values. ldndc defines for each stratum one soil layer discretization. 
  good choice would be:
  depth <= 5 cm: 
  5 cm < depth <= 20 cm: 
  20 cm < depth <= 50 cm: 
  50 cm <  depth

**Comment by cwerner** [comment]
**NOTE:** extra strata will be handled in another post-processing script for the Vietnam project. Default behaviour of `dlsc` will stay the same: soil layers are added according to provided depth info in ISRIC-WISE soil database
